trigger:
- '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
  - npm

variables:
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVer: '3.1.300'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1 SDK $(dotnetSdkVer)'
  inputs:
    packageType: sdk
    version: '$(dotnetSdkVer)'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: $(wwwrootDir)

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'
  
- task: PublishBuildArtifacts@1
  displayName: 'Published Artifact: drop'
  condition: succeeded()